sudo: required
services:
  - docker

before_install:
  - docker build -t davekhim/re-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true davekhim/re-docker-react npm run test -- --coverage